# Generated by Django 5.2.8 on 2025-12-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.CharField(default='Неуказанно', max_length=50, verbose_name='Страна производителя'),
        ),
    ]
