# Generated by Django 5.2.8 on 2025-12-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_car_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bonus_points',
        ),
    ]
