# Generated by Django 5.2.8 on 2025-12-22 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_profile_bonus_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='tuning_type',
            field=models.CharField(choices=[('base', 'Базовая комплектация'), ('standard', 'Standard Tuning (+15%)'), ('premium', 'Premium Tuning (+30%)')], default='base', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tuning_type',
            field=models.CharField(choices=[('base', 'Базовая комплектация'), ('standard', 'Standard Tuning (+15%)'), ('premium', 'Premium Tuning (+30%)')], default='base', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.car'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
